project_name: hibp-checker

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: hibp-checker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: sthayduk
    name: hibp-checker
